// Code generated by entc, DO NOT EDIT.

package recipe

import (
	"adomeit.xyz/recipe/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSlug), v))
	})
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// Ingredientslist applies equality check predicate on the "ingredientslist" field. It's identical to IngredientslistEQ.
func Ingredientslist(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIngredientslist), v))
	})
}

// Instructions applies equality check predicate on the "instructions" field. It's identical to InstructionsEQ.
func Instructions(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldInstructions), v))
	})
}

// Nutrition applies equality check predicate on the "nutrition" field. It's identical to NutritionEQ.
func Nutrition(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNutrition), v))
	})
}

// Servings applies equality check predicate on the "servings" field. It's identical to ServingsEQ.
func Servings(v int) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldServings), v))
	})
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSlug), v))
	})
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSlug), v))
	})
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.Recipe {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Recipe(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSlug), v...))
	})
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.Recipe {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Recipe(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSlug), v...))
	})
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSlug), v))
	})
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSlug), v))
	})
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSlug), v))
	})
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSlug), v))
	})
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSlug), v))
	})
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSlug), v))
	})
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSlug), v))
	})
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSlug), v))
	})
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSlug), v))
	})
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldName), v))
	})
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Recipe {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Recipe(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldName), v...))
	})
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Recipe {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Recipe(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldName), v...))
	})
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldName), v))
	})
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldName), v))
	})
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldName), v))
	})
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldName), v))
	})
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldName), v))
	})
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldName), v))
	})
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldName), v))
	})
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldName), v))
	})
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldName), v))
	})
}

// IngredientslistEQ applies the EQ predicate on the "ingredientslist" field.
func IngredientslistEQ(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIngredientslist), v))
	})
}

// IngredientslistNEQ applies the NEQ predicate on the "ingredientslist" field.
func IngredientslistNEQ(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldIngredientslist), v))
	})
}

// IngredientslistIn applies the In predicate on the "ingredientslist" field.
func IngredientslistIn(vs ...string) predicate.Recipe {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Recipe(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldIngredientslist), v...))
	})
}

// IngredientslistNotIn applies the NotIn predicate on the "ingredientslist" field.
func IngredientslistNotIn(vs ...string) predicate.Recipe {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Recipe(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldIngredientslist), v...))
	})
}

// IngredientslistGT applies the GT predicate on the "ingredientslist" field.
func IngredientslistGT(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldIngredientslist), v))
	})
}

// IngredientslistGTE applies the GTE predicate on the "ingredientslist" field.
func IngredientslistGTE(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldIngredientslist), v))
	})
}

// IngredientslistLT applies the LT predicate on the "ingredientslist" field.
func IngredientslistLT(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldIngredientslist), v))
	})
}

// IngredientslistLTE applies the LTE predicate on the "ingredientslist" field.
func IngredientslistLTE(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldIngredientslist), v))
	})
}

// IngredientslistContains applies the Contains predicate on the "ingredientslist" field.
func IngredientslistContains(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldIngredientslist), v))
	})
}

// IngredientslistHasPrefix applies the HasPrefix predicate on the "ingredientslist" field.
func IngredientslistHasPrefix(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldIngredientslist), v))
	})
}

// IngredientslistHasSuffix applies the HasSuffix predicate on the "ingredientslist" field.
func IngredientslistHasSuffix(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldIngredientslist), v))
	})
}

// IngredientslistEqualFold applies the EqualFold predicate on the "ingredientslist" field.
func IngredientslistEqualFold(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldIngredientslist), v))
	})
}

// IngredientslistContainsFold applies the ContainsFold predicate on the "ingredientslist" field.
func IngredientslistContainsFold(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldIngredientslist), v))
	})
}

// InstructionsEQ applies the EQ predicate on the "instructions" field.
func InstructionsEQ(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldInstructions), v))
	})
}

// InstructionsNEQ applies the NEQ predicate on the "instructions" field.
func InstructionsNEQ(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldInstructions), v))
	})
}

// InstructionsIn applies the In predicate on the "instructions" field.
func InstructionsIn(vs ...string) predicate.Recipe {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Recipe(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldInstructions), v...))
	})
}

// InstructionsNotIn applies the NotIn predicate on the "instructions" field.
func InstructionsNotIn(vs ...string) predicate.Recipe {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Recipe(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldInstructions), v...))
	})
}

// InstructionsGT applies the GT predicate on the "instructions" field.
func InstructionsGT(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldInstructions), v))
	})
}

// InstructionsGTE applies the GTE predicate on the "instructions" field.
func InstructionsGTE(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldInstructions), v))
	})
}

// InstructionsLT applies the LT predicate on the "instructions" field.
func InstructionsLT(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldInstructions), v))
	})
}

// InstructionsLTE applies the LTE predicate on the "instructions" field.
func InstructionsLTE(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldInstructions), v))
	})
}

// InstructionsContains applies the Contains predicate on the "instructions" field.
func InstructionsContains(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldInstructions), v))
	})
}

// InstructionsHasPrefix applies the HasPrefix predicate on the "instructions" field.
func InstructionsHasPrefix(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldInstructions), v))
	})
}

// InstructionsHasSuffix applies the HasSuffix predicate on the "instructions" field.
func InstructionsHasSuffix(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldInstructions), v))
	})
}

// InstructionsEqualFold applies the EqualFold predicate on the "instructions" field.
func InstructionsEqualFold(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldInstructions), v))
	})
}

// InstructionsContainsFold applies the ContainsFold predicate on the "instructions" field.
func InstructionsContainsFold(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldInstructions), v))
	})
}

// NutritionEQ applies the EQ predicate on the "nutrition" field.
func NutritionEQ(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNutrition), v))
	})
}

// NutritionNEQ applies the NEQ predicate on the "nutrition" field.
func NutritionNEQ(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldNutrition), v))
	})
}

// NutritionIn applies the In predicate on the "nutrition" field.
func NutritionIn(vs ...string) predicate.Recipe {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Recipe(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldNutrition), v...))
	})
}

// NutritionNotIn applies the NotIn predicate on the "nutrition" field.
func NutritionNotIn(vs ...string) predicate.Recipe {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Recipe(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldNutrition), v...))
	})
}

// NutritionGT applies the GT predicate on the "nutrition" field.
func NutritionGT(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldNutrition), v))
	})
}

// NutritionGTE applies the GTE predicate on the "nutrition" field.
func NutritionGTE(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldNutrition), v))
	})
}

// NutritionLT applies the LT predicate on the "nutrition" field.
func NutritionLT(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldNutrition), v))
	})
}

// NutritionLTE applies the LTE predicate on the "nutrition" field.
func NutritionLTE(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldNutrition), v))
	})
}

// NutritionContains applies the Contains predicate on the "nutrition" field.
func NutritionContains(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldNutrition), v))
	})
}

// NutritionHasPrefix applies the HasPrefix predicate on the "nutrition" field.
func NutritionHasPrefix(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldNutrition), v))
	})
}

// NutritionHasSuffix applies the HasSuffix predicate on the "nutrition" field.
func NutritionHasSuffix(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldNutrition), v))
	})
}

// NutritionEqualFold applies the EqualFold predicate on the "nutrition" field.
func NutritionEqualFold(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldNutrition), v))
	})
}

// NutritionContainsFold applies the ContainsFold predicate on the "nutrition" field.
func NutritionContainsFold(v string) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldNutrition), v))
	})
}

// ServingsEQ applies the EQ predicate on the "servings" field.
func ServingsEQ(v int) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldServings), v))
	})
}

// ServingsNEQ applies the NEQ predicate on the "servings" field.
func ServingsNEQ(v int) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldServings), v))
	})
}

// ServingsIn applies the In predicate on the "servings" field.
func ServingsIn(vs ...int) predicate.Recipe {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Recipe(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldServings), v...))
	})
}

// ServingsNotIn applies the NotIn predicate on the "servings" field.
func ServingsNotIn(vs ...int) predicate.Recipe {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Recipe(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldServings), v...))
	})
}

// ServingsGT applies the GT predicate on the "servings" field.
func ServingsGT(v int) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldServings), v))
	})
}

// ServingsGTE applies the GTE predicate on the "servings" field.
func ServingsGTE(v int) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldServings), v))
	})
}

// ServingsLT applies the LT predicate on the "servings" field.
func ServingsLT(v int) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldServings), v))
	})
}

// ServingsLTE applies the LTE predicate on the "servings" field.
func ServingsLTE(v int) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldServings), v))
	})
}

// HasIngredients applies the HasEdge predicate on the "ingredients" edge.
func HasIngredients() predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(IngredientsTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, IngredientsTable, IngredientsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIngredientsWith applies the HasEdge predicate on the "ingredients" edge with a given conditions (other predicates).
func HasIngredientsWith(preds ...predicate.Ingredient) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(IngredientsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, IngredientsTable, IngredientsPrimaryKey...),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Recipe) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Recipe) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Recipe) predicate.Recipe {
	return predicate.Recipe(func(s *sql.Selector) {
		p(s.Not())
	})
}
