name: Check Gateway Build

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'gateway/**'
      - 'shared/**'

jobs:
  test:
    uses: ./.github/workflows/go-test.yml
    with:
      directory: ./gateway
