name: Apply Terraform 

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
      - 'forager/**'
      - 'gateway/**'
      - 'user/**'
      - 'main.tf'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1

      - name: Init Terraform
        run: terraform init -backend-config="conn_str=${{ secrets.TF_BACKEND }}"

      - name: Apply Terraform
        run: terraform apply -auto-approve
        env:
          TF_VAR_name: adtest
          TF_VAR_FOODDATA_TOKEN: ${{ secrets.FOODDATA_TOKEN }}
          TF_VAR_GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          TF_VAR_GCP_SECRET_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
