name: Check User Service Build

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'user/**'
      - 'shared/**'

jobs:
  test:
    uses: ./.github/workflows/go-test.yml
    with:
      directory: ./user
